### PR TITLE
Update for the rocket 0.5 release candidate

### PR DESCRIPTION
**Pull request by fenhl**
You may want to merge this into a separate pre-release branch since this technically adds a dependency on a pre-release version of a crate (though according to [the crates.io stats](https://crates.io/crates/rocket) most people are using rocket 0.5 already).

### CODE REVIEW

**Review by genusistimelord — APPROVED** [review]
These changes do follow rocket 0.5 new API and looks to be done correctly. I saw Sergio is working on Rocket again so you might see a full release of 0.5 soon.

**Comment by kotovalexarian** [comment]
I'll look today or in the weekend

**Comment by kotovalexarian** [comment]
@fenhl, @genusistimelord, hello. Sorry for very long delay. I've reviewed the patch. Unfortunately, crate `rocket_contrib` has no release candidate for 0.5.0. I use this crate for Handlebars templates in [example](/examples/minimal/). I'll try to rewrite the example without this crate.

**Comment by fenhl** [comment]
The template support has been moved to [`rocket_dyn_templates`](https://crates.io/crates/rocket_dyn_templates).

**Review by kotovalexarian — APPROVED** [review]

**Comment by fenhl** [comment]
Any chance we could get a new release on crates.io now that rocket 0.5 is released?

**Pull request merged**
